backend:
  name: github
  repo: Fabi000n/kochbuch
  branch: main

local_backend: true

media_folder: "static/images/uploads" 
public_folder: "/images/uploads

collections:
  - name: rezepte
    label: Rezepte
    folder: content/rezepte
    create: true
    extension: "md"
    slug: "{{slug}}"
    format: frontmatter
    frontmatter_delimiter: "---"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: false }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - label: "Zutaten"
        name: "ingredients"
        widget: "list"
        field: { label: "Zutat", name: "item", widget: "string" }
      - { label: "Vorbereitungszeit (min)", name: "prepTime", widget: "number", value_type: "int", min: 0, step: 5, required: false }
      - { label: "Kochzeit (min)", name: "cookTime", widget: "number", value_type: "int", min: 0, step: 5, required: false }
      - { label: "Portionen", name: "servings", widget: "number", value_type: "int", min: 1, step: 1, required: false }
      - { label: "Inhalt (Markdown)", name: "body", widget: "markdown" }
